AWSTemplateFormatVersion: "2010-09-09"
Description: "NAT Gateway"
Parameters:
  SsubnetCidr:
    Type: String
    Description: Ip
    Default: 10.0.0.4/16
Resources:
  SNatGateWayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: !Ref SsubnetCidr
  HarishNatGateWay:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt SNatGateWayEIP.AllocationId
      SubnetId: !ImportValue ImportSubnetId3
      Tags:
        - Key: User
          Value: karneedi.harish
  HarishSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.8/24
      AvailabilityZone: us-east-1a
      Tags:
        - Key: User
          Value: karneedi.harish
      VpcId: !ImportValue ImportVpcId3
  HarishRouteTable1:
      Type: AWS::EC2::RouteTable
      Properties: 
        VpcId: !ImportValue ImportVpcId3
  HarishRoute1:
      Type: AWS::EC2::Route
      Properties: 
        NatGatewayId: !Ref HarishNatGateWay
        RouteTableId: !Ref HarishRouteTable1
        DestinationCidrBlock: 0.0.0.0/16
  SRouteNATGateway:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref HarishRouteTable1
      DestinationCidrBlock: '0.0.0.0/16'
      NatGatewayId: !Ref HarishNatGateWay
  SurekhaEc2Instance1:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-05fa00d4c63e32376
      AvailabilityZone: us-east-1a
      KeyName: HarishKeyPair
      Tags:
        - Key: User
          Value: karneedi.harish
      SubnetId: !Ref HarishSubnet2