AWSTemplateFormatVersion: "2010-09-09"
Description: "Network ACL for VPC"
Parameters:
  SsubnetCidr:
    Type: String
    Description: Ip
    Default: 10.0.0.8/16
Resources:
  SNetworkAcl:
    Type: AWS::EC2::NetworkAcl
    Properties:
      VpcId: !ImportValue ImportVpcId3
      Tags:
        - Key: User
          Value: karneedi.harish
  HarishSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties: 
      GroupDescription: Security Group for EC2
      GroupName: Harish
      SecurityGroupIngress:
        - IpProtocol: All
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8
          ToPort: 22
          CidrIp: 192.0.2.0/24
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 2
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: User
          Value: karneedi.harish
      VpcId: !ImportValue ImportVpcId3