Parameters:
  SubnetCidr:
      Type: String
      Description: enter ip
      Default: 10.0.0.8/16
Resources:
  MyVpc20:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: !Ref SubnetCidr
        Tags:
            - Key: User
              Value: Jatin.x        
            - Key: stelligent-u-lesson
              Value: '4'
            - Key: stelligent-u-lab
              Value: '4.1.1'
  MySubnet20:
      Type: AWS::EC2::Subnet
      Properties:
        CidrBlock: 10.0.2.8/24
        AvailabilityZone: us-east-1a
        Tags:
            - Key: User
              Value: Jatin.x         
            - Key: stelligent-u-lesson
              Value: '4'
            - Key: stelligent-u-lab
              Value: '4.1.1'
        VpcId: !Ref MyVpc20
Outputs:
  MyVpcOutputs:
      Value: !Ref MyVpc20
  MySubnetOutputs:
      Value: !Ref MySubnet20