AWSTemplateFormatVersion: "2010-09-09"
Description: "Cross-Referencing Resources within a Template"
Parameters:
  UserName:
    Type: String
    Default: priyanka2344
Resources: 
  MyIamUser:
    Type: AWS::IAM::User
    Properties: 
      UserName: priyanka2344 
  IamManagedPolicy:
    Type: AWS::IAM::ManagedPolicy
    Description: "Policy for s3"
    Properties:
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Action: 
              - "s3:ReadOnlyAccess" 
              - "s3:ListBucket"
              - "s3:Get*"
            Resource: "*" 
      Users: 
        - !Ref UserName

#command: create-stack --no-verify-ssl --profile temp --stack-name priyankas1 --template-body "file://C:\Users\kodavati.priyanka\Desktop\New folder (2)\lab1.2\lab1.2.1.yaml" --capabilities CAPABILITY_NAMED_IAM
#{
#    "StackId": "arn:aws:cloudformation:us-east-1:324320755747:stack/priyankas1/b04bacd0-2b9e-11ed-b2fb-0acb6cbd57e3"
#}

           


      

    
    