AWSTemplateFormatVersion: "2010-09-09"
Description: "Managed Policy"
Resources:
  SurekhaRole:
    Type: AWS::IAM::Role    
    Properties:
      Description: managed policy
      RoleName: SurekhaRole2
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess


