AWSTemplateFormatVersion: "2010-09-09"
Description: "Customer Managed Policy"
Resources:
  IamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - iam.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InlinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - "iam:Get*"
                - "iam:List*"
                Resource: "arn:aws:iam::324320755747:role/ReadOnlyRole"
      RoleName: ReadOnlyRole