AWSTemplateFormatVersion: "2010-09-09"
Description: "Object Lifecycles"
Resources:
  S3Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          - Id: StandardIARule
            Prefix: STANDARD_IA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: "STANDARD_IA"
          - Id: GlacierRule
            Prefix: glacier
            Status: Enabled
            Transitions:
              - TransitionInDays: 90
                StorageClass: "GLACIER"
             
#{
#    "StackId": "arn:aws:cloudformation:us-west-2:324320755747:stack/priyankas2/f6d72f50-2f75-11ed-9ed0-0a3fc127317d"

#}