AWSTemplateFormatVersion: "2010-09-09"
Description: "addingpriviledges"
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: kknewtp
  IamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - iam.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InlinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - "iam:Get*"
                - "iam:List*"
                Resource: "arn:aws:iam::324320755747:role/khan-2-IamRootRole-AVMXEUYPB28L"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      RoleName: khan-2-IamRootRole-AVMXEUYPB28L
  
