AWSTemplateFormatVersion: "2010-09-09"
Description: "Updation of Stack with Another AMI"
Resources:
  Ec2Instan1:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-0910b65723f27f156
      AvailabilityZone: us-east-1a
      KeyName: SurekhaKeyPair
      Tags:
        - Key: User
          Value: surekha.janjanam
  Ec2Instan2:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-08c40ec9ead489470
      AvailabilityZone: us-east-1a
      KeyName: SurekhaKeyPair
      Tags:
        - Key: User
          Value: surekha.janjanam
  JvtsInstance:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData: 
        InstanceType: !Ref Ec2Instan1
        ImageId: ami-0910b65723f27f156
        InstanceType: !Ref Ec2Instan2
        ImageId: ami-08c40ec9ead489470
      LaunchTemplateName: SLT
          
