AWSTemplateFormatVersion: "2010-09-09"
Description: "EIP"
Resources:
  Ec2Instan2:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-08c40ec9ead489470
      AvailabilityZone: us-east-1a
      KeyName: SurekhaKeyPair
      SecurityGroupIds: 
          - !Ref SSGLaunchTemplate
      Tags:
        - Key: User
          Value: surekha.janjanam
  Ec2EIP:
    Type: AWS::EC2::EIP
    Properties: 
      InstanceId: !Ref Ec2Instan2
  Ec2EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties: 
      EIP: !Ref Ec2EIP
      InstanceId: !Ref Ec2Instan2
  JvtsInstance:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData: 
        InstanceType: !Ref Ec2Instan2
        ImageId: ami-08c40ec9ead489470
        SecurityGroupIds:
          - sg-06143f7dc9d7e81df
        KeyName: SurekhaKeyPair
      LaunchTemplateName: !Ref SSGLaunchTemplate
  SSGLaunchTemplate:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SeurityGroup to launch template
      SecurityGroupIngress:
        - IpProtocol: icmp
          FromPort: 8
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags: 
        - Key: User
          Value: surekha.janjanam
Outputs:
  PublicIp:
    Value: !GetAtt Ec2Instan2.PublicIp
