AWSTemplateFormatVersion: '2010-09-09'
Description: SSH Keys
Resources:
  MyInstance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ee23bfc74a881de5
      InstanceType: t2.micro
      KeyName: priyankakeypair
      SecurityGroupIds:
        - !Ref SecurityGroup
  EIP:
    Type: AWS::EC2::EIP
    Properties: 
      InstanceId: !Ref MyInstance2
  EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      EIP: !Ref EIP
      InstanceId: !Ref MyInstance2
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group to test ping
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0    
  MyLaunchTemplate1:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: MyLaunchTemplate2
      LaunchTemplateData:  
        InstanceType: !Ref MyInstance2
        ImageId: ami-0ee23bfc74a881de5
        SecurityGroupIds:
          - sg-025e131b17c25c001
        KeyName: priyankakeypair
Outputs:
  PublicIP4:
    Value: !GetAtt MyInstance2.PublicIp

