AWSTemplateFormatVersion: '2010-09-09'
Description: SSH Keys
Resources:
  MyInstance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ee23bfc74a881de5
      InstanceType: t2.micro
      KeyName: priyankakeypair
  EIP:
    Type: AWS::EC2::EIP
    Properties: 
      InstanceId: !Ref MyInstance2
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group to test ping
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.0.0/24
        - IpProtocol: icmp
          FromPort: 8
          ToPort: -1
          CidrIp: 10.0.0.0/24      
  MyLaunchTemplate1:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: MyLaunchTemplate2
      LaunchTemplateData:  
        InstanceType: !Ref MyInstance2
        ImageId: ami-0ee23bfc74a881de5
        SecurityGroupIds:
            - sg-041b67a30564f5a42
        KeyName: priyankakeypair
Outputs:
  PublicIP4:
    Value: !GetAtt MyInstance2.PublicIp

