AWSTemplateFormatVersion: '2010-09-09'
Description: Launching Two ec2 Instance
Resources:
  MyInstance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0b3e423be2b1ed909 
      InstanceType: t2.micro
      KeyName: priyakeypair
  MyInstance2:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0ee23bfc74a881de5
      InstanceType: t2.micro
  MyLaunchTemplate1:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: MyLaunchTemplate2
      LaunchTemplateData:
        InstanceType: !Ref MyInstance1
        ImageId: ami-0b3e423be2b1ed909  
        InstanceType: !Ref MyInstance2
        ImageId: ami-0ee23bfc74a881de5
        KeyName: priyapair