AWSTemplateFormatVersion: "2010-09-09"
Description: "NAT Gateway"
Parameters:
  KksubnetCidr:
    Type: String
    Description: Ip
    Default: 10.0.0.4/16
Resources:
  KhanNatGateWayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: !Ref KksubnetCidr
  KhanNatGateWay:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt KhanNatGateWayEIP.AllocationId
      SubnetId: !ImportValue ImportSubnetIdkk
      Tags:
        - Key: User
          Value: Kamran.khan
  KhanSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.8/24
      AvailabilityZone: us-east-1a
      Tags:
        - Key: User
          Value: Kamran.khan
      VpcId: !ImportValue ImportVpcId
  KhanRouteTable1:
      Type: AWS::EC2::RouteTable
      Properties: 
        VpcId: !ImportValue ImportVpcId
  KhanRoute1:
      Type: AWS::EC2::Route
      Properties: 
        NatGatewayId: !Ref KhanNatGateWay
        RouteTableId: !Ref KhanRouteTable1
        DestinationCidrBlock: 0.0.0.0/16
  KhanRouteNATGateway:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref KhanRouteTable1
      DestinationCidrBlock: '0.0.0.0/16'
      NatGatewayId: !Ref KhanNatGateWay
  KhanEc2Instance1:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-0c2ab3b8efb09f272
      AvailabilityZone: us-east-1a
      KeyName: KamranKeyPair
      Tags:
        - Key: User
          Value: Kamran.khan
      SubnetId: !Ref KhanSubnet2