AWSTemplateFormatVersion: "2010-09-09"
Description: "Applying Internet Gateway"
Parameters:
    KkSubnetCidr:
      Type: String
      Description: Entering IP
      Default: 10.0.0.2/16
Resources:
    KhanVpc:
      Type: AWS::EC2::VPC
      Properties:
        CidrBlock: !Ref KkSubnetCidr
        Tags:
          - Key: User
            Value: kamran.khan        
          - Key: stelligent-u-lesson
            Value: '4'
          - Key: stelligent-u-lab
            Value: '4.1.2'
    KhanSubnet:
      Type: AWS::EC2::Subnet
      Properties:
          CidrBlock: 10.0.0.4/24
          AvailabilityZone: us-west-2a
          Tags:
            - Key: User
              Value: kamran.khan        
            - Key: stelligent-u-lesson
              Value: '4'
            - Key: stelligent-u-lab
              Value: '4.1.2'
          VpcId: !Ref KhanVpc
    KhanInternetGateway:
      Type: AWS::EC2::InternetGateway
      Properties:
          Tags:
            - Key: User
              Value: kamran.khan
    KhanVPCGA:
      Type: AWS::EC2::VPCGatewayAttachment
      Properties:
        InternetGatewayId: !Ref KhanInternetGateway
        VpcId: !Ref KhanVpc
    KhanRouteTable:
      Type: AWS::EC2::RouteTable
      Properties:
          VpcId: !Ref KhanVpc
    KhanRoute:
      Type: AWS::EC2::Route
      Properties:
          GatewayId: !Ref KhanInternetGateway
          RouteTableId: !Ref KhanRouteTable
          DestinationCidrBlock: 0.0.0.0/0

