AWSTemplateFormatVersion: "2010-09-09"
Description: "Object Lifecycles for S3"
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Enabled      
      LifecycleConfiguration:
        Rules:
          - Id: Rule1
            Prefix: STANDARD_IA
            Status: Enabled
            Transitions:
              - TransitionInDays: 30
                StorageClass: "STANDARD_IA"
          - Id: Rule2
            Prefix: Glacier
            Status: Enabled
            Transitions:
              - TransitionInDays: 90
                StorageClass: "GLACIER"
  
         - Id: Rule3
            Prefix: Non-current
            Status: Enabled
            Transitions:
              - TransitionInDays: 7
                StorageClass: "Non-current"