AWSTemplateFormatVersion: "2010-09-09"
Description: "Trust Policy For IAM"
Parameters:
  ManagedPolicy:
    Type: String
    Default: arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
Resources:
  IamRootRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
               AWS: arn:aws:iam::324320755747:root
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref ManagedPolicy