AWSTemplateFormatVersion: "2010-09-09"
Description: "Test Instance"
Parameters:
  InstanceTypeParameter:
    Type: String
    Default: t2.micro
    AllowedValues:
      - t2.micro
      - m1.small
      - m1.large
    Description: Type of Instance
  InstanceImageId:
    Type: String
    Default: ami-05fa00d4c63e32376
  InstanceKeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Default: priyankakeypair
Resources:
  Ec2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: !Ref InstanceTypeParameter
      ImageId: !Ref InstanceImageId
      AvailabilityZone: us-east-1a
      KeyName: !Ref InstanceKeyName
      Tags:
        - Key: User
          Value: kodavati.priyanka
        - Key: stelligent.kodavati.priyanka
          Value: '4'
        - Key: stelligent-u-labs
          Value: '4.1.4'
      SubnetId: !ImportValue ImportSubnetId 
Outputs:
  InstanceId:
    Value: !Ref Ec2Instance
  PrivateIp:
    Value: !GetAtt Ec2Instance.PrivateIp
