AWSTemplateFormatVersion: '2010-09-09'
Description:  Launch Template
Resources:
  MyInstance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09a41e26df464c548  
      InstanceType: t2.micro
      KeyName: priyakeypair
  MyLaunchTemplate1:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: MyLaunchTempl
      LaunchTemplateData:
        InstanceType: !Ref MyInstance1
        ImageId: ami-09a41e26df464c548
        KeyName: priyapair
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties: 
      AutoScalingGroupName: my-Scaling1
      AvailabilityZones: 
        - us-east-1e
      InstanceId: !Ref MyInstance1
      MaxSize: 1
      MinSize: 1
      DesiredCapacity: 1 

    