AWSTemplateFormatVersion: '2010-09-09'
Description: Updation Policy
Resources:
  MyInstance1:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-09a41e26df464c548  
      InstanceType: t2.micro
      KeyName: priyakeypair
  MyLaunchConfiguration:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-09a41e26df464c548 
      InstanceType: t2.medium
      KeyName: priyakeypair
      InstanceId: !Ref MyInstance1
  AutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties: 
      LaunchConfigurationName: !Ref MyLaunchConfiguration
      AutoScalingGroupName: PAutoScaling
      AvailabilityZones: 
        - us-east-1e
      MaxSize: 1
      MinSize: 1
      DesiredCapacity: 1
  