AWSTemplateFormatVersion: "2010-09-09"
Description: "Launch Template"
Resources:
  Ec2DebianInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-09a41e26df464c548
      AvailabilityZone: us-east-1a
      KeyName: HarishKeyPair
      Tags:
        - Key: User
          Value: karneedi.harish
  MyInstance:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: t2.micro
        ImageId: ami-09a41e26df464c548
        KeyName: HarishKeyPair
      LaunchTemplateName: HarishLaunchTemplate
  HarishAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: Harish
      AvailabilityZones:
        - us-east-1a
      LaunchTemplate:
          LaunchTemplateName: HarishLaunchTemplate
          Version: !GetAtt MyInstance.LatestVersionNumber
      MaxSize: 1
      MinSize: 1
      DesiredCapacity: 1