AWSTemplateFormatVersion: "2010-09-09"
Description: "ASG Update Policy"
Resources:
  Ec2DebianInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-09a41e26df464c548
      AvailabilityZone: us-east-1a
      KeyName: HarishKeyPair
      Tags:
        - Key: User
          Value: karneedi.harish
  HarishAutoScalingConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties:
      ImageId: ami-09a41e26df464c548
      InstanceId: !Ref Ec2DebianInstance
      InstanceType: t2.medium
  HarishAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties:
      AutoScalingGroupName: Harish
      AvailabilityZones:
        - us-east-1a
      LaunchConfigurationName: !Ref HarishAutoScalingConfig
      MaxSize: 1
      MinSize: 1
      DesiredCapacity: 1