AWSTemplateFormatVersion: "2010-09-09"
Description: "ASG Update Policy"
Resources:
  Ec2Instan1:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-09a41e26df464c548
      AvailabilityZone: us-east-1a
      KeyName: SurekhaKeyPair
      Tags:
        - Key: User
          Value: surekha.janjanam
  LaunchInstance:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData: 
        InstanceType: t2.micro
        ImageId: ami-09a41e26df464c548
        KeyName: SurekhaKeyPair
      LaunchTemplateName: LaunchTemplate
  SurekhaAutoScalingConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties: 
      ImageId: ami-09a41e26df464c548
      InstanceId: !Ref Ec2Instan1
      InstanceType: t2.medium
  SurekhaAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties: 
      AutoScalingGroupName: Jvts
      AvailabilityZones: 
        - us-east-1a
      LaunchTemplate:
          LaunchTemplateName: LaunchTemplate
          Version: !GetAtt LaunchInstance.LatestVersionNumber
      MaxSize: 1
      MinSize: 1
      DesiredCapacity: 1