AWSTemplateFormatVersion: "2010-09-09"
Description: "Launch Config and ASG in CFN"
Resources:
  Ec2Instan1:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-09a41e26df464c548
      AvailabilityZone: us-east-1a
      KeyName: SurekhaKeyPair
      Tags:
        - Key: User
          Value: surekha.janjanam
  SurekhaAutoScalingConfig:
    Type: AWS::AutoScaling::LaunchConfiguration
    Properties: 
      ImageId: ami-09a41e26df464c548
      InstanceId: !Ref Ec2Instan1
      InstanceType: t2.micro
  SurekhaAutoScalingGroup:
    Type: AWS::AutoScaling::AutoScalingGroup
    Properties: 
      AutoScalingGroupName: SAG
      AvailabilityZones: 
        - us-east-1a
      InstanceId: !Ref Ec2Instan1
      MaxSize: 1
      MinSize: 1
      DesiredCapacity: 1
      