AWSTemplateFormatVersion: "2010-09-09"
Description: "Versioning of s3 bucket"
Parameters:
  BucketName:
    Type: String
    Default: stelligent-u-jatin.x.labs
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled