AWSTemplateFormatVersion: "2010-09-09"
Description: "Creation of IAM Role"
Resources:
  IamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - iam.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InlinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 
                - "iam:Get*"
                - "iam:List*"
                Resource: "*"
      RoleName: ReadOnlyPriya
#   {
    #"StackId": "arn:aws:cloudformation:us-west-2:324320755747:stack/priyankas1/24adeb10-3009-11ed-b3a1-0a344d7b5d4f"
#}
