AWSTemplateFormatVersion: "2010-09-09"
Description: "Managedpolicy to user"
Parameters:
  UserName:
    Type: String
    Default: Jatin6
  UserPassword:
    Type: String
    Default: Jatin@8650
Resources:
  IamUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      LoginProfile:
        Password: !Ref UserPassword
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
Outputs:
  OutputName:
    Description: "getting username"
    Value: !Ref IamUser
    Export:
      Name: "ManagedPolicyArns"