AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 Tagging Resources"
Parameters:
  BucketName:
    Type: String
    Default: stelligent-u-janjanam.surekha.labs
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      Tags:
        - Key: "Owner"
          Value: "surekha"
        - Key: "Owner2"
          Value: "jvts"


       
