AWSTemplateFormatVersion: "2010-09-09"
Description: "Unrestricted access to a service"
Resources:
  S3Bucket1:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: hari111
  S3Bucket2:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: hari222
  MyPolicy11:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Customer Managed Policy"
      ManagedPolicyName: ManagedPolicy3
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
            - "s3:*"
            Resource:
            - "!Sub arn:aws:s3:::${S3Bucket1}"
            - "!Sub arn:aws:s3:::${S3Bucket1}/*"
      Users:
        - "karneedi.harish.labs"
  MyPolicy22:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Customer Managed Policy"
      ManagedPolicyName: ManagedPolicy4
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
            - "s3:Get*"
            - "s3:List*"
            Resource:
            - "!Sub arn:aws:s3:::${S3Bucket2}"
            - "!Sub arn:aws:s3:::${S3Bucket2}/*"
      Users:
        - "karneedi.harish.labs"
  IamRole123:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              "AWS": "arn:aws:iam::324320755747:user/karneedi.harish.labs"
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - !Ref MyPolicy11
        - !Ref MyPolicy22