AWSTemplateFormatVersion: "2010-09-09"
Description: "Launch EC2 Instances"
Resources:
  JatinEc2InstanWindow:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-0b3e423be2b1ed909
      AvailabilityZone: us-east-1a
      KeyName: JatinKeyPair
      Tags:
        - Key: User
          Value: Jatin.x
      SubnetId: !ImportValue ImportSubnetId
  JatinEc2InstanUbuntu:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-08c40ec9ead489470
      AvailabilityZone: us-east-1a
      KeyName: JatinKeyPair
      Tags:
        - Key: User
          Value: Jatin.x
      SubnetId: !ImportValue ImportSubnetId
  JvtsInstance1:
    Type: AWS::EC2::LaunchTemplate
    Properties: 
      LaunchTemplateData: 
        InstanceType: !Ref JatinEc2InstanWindow
        ImageId: ami-0b3e423be2b1ed909
        InstanceType: !Ref JatinEc2InstanUbuntu
        ImageId: ami-08c40ec9ead489470
      LaunchTemplateName: JATIN