AWSTemplateFormatVersion: "2010-09-09"
Description: "EIP"
Resources:
  Ec2InstanceUbuntu:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0ee23bfc74a881de5
      AvailabilityZone: us-east-1a
      KeyName: HarishKeyPair
      SecurityGroupIds:
        - !Ref HSGLaunchTemplate
      Tags:
        - Key: User
          Value: karneedi.harish    
  Ec2EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref Ec2InstanceUbuntu
  Ec2EIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      EIP: !Ref Ec2EIP
      InstanceId: !Ref Ec2InstanceUbuntu
  HarishInstance:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: !Ref Ec2InstanceUbuntu
        ImageId: ami-0ee23bfc74a881de5
        SecurityGroupIds:
          - sg-0eb360a73e6b080fe
        KeyName: HarishKeyPair        
      LaunchTemplateName: !Ref HSGLaunchTemplate
  HSGLaunchTemplate:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SeurityGroup to launch template
      SecurityGroupIngress:
        - IpProtocol: icmp
          FromPort: 8
          ToPort: -1
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: User
          Value: karneedi.harish
Outputs:
  PublicIp:
    Value: !GetAtt Ec2InstanceUbuntu.PublicIp