AWSTemplateFormatVersion: "2010-09-09"
Description: "SSH Keys for ec2 instance"
Resources:
  Ec2InstanceUbuntu:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0ee23bfc74a881de5
      AvailabilityZone: us-east-1a
      KeyName: HarishKeyPair1
      Tags:
        - Key: User
          Value: karneedi.harish
      SecurityGroupIds:
          - !Ref HSGLaunchTemplate
  Ec2EIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref Ec2InstanceUbuntu
  HarishInstance:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateData:
        InstanceType: !Ref Ec2InstanceUbuntu
        ImageId: ami-0ee23bfc74a881de5
        KeyName: HarishKeyPair1
        SecurityGroupIds:
          - sg-03e59aee1d518680c
      LaunchTemplateName: !Ref HSGLaunchTemplate
  HSGLaunchTemplate:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SeurityGroup to launch template
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: User
          Value: karneedi.harish
Outputs:
  PublicIp:
    Value: !GetAtt Ec2InstanceUbuntu.PublicIp