AWSTemplateFormatVersion: "2010-09-09"
Description: "Test Instance"
Parameters:
  SsubnetCidr:
    Type: String
    Description: Ip
    Default: 10.0.0.8/16
Resources:
  SurekhaEc2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      AvailabilityZone: us-east-1
      InstanceType: t2.micro
      ImageId: ami-79fd7eee
      KeyName: String
  SurekhaVpc2:
    Type: AWS::EC2::VPC
    Properties: 
      CidrBlock: !Ref SsubnetCidr
      Tags:
        - Key: User
          Value: surekha.janjanam
  SurekhaSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.0.2/24
      AvailabilityZone: us-west-2a
      Tags:
        - Key: User
          Value: surekha.janjanam
      VpcId: !Ref SurekhaVpc2
Outputs:
  MyVpcOp:
    Value: !Ref SurekhaVpc2
  MySubnetOp:
    Value: !Ref SurekhaSubnet2
  OutputEc2:
  InstanceID:
    Description: The Instance ID
    Value: !Ref SurekhaEc2Instance
