AWSTemplateFormatVersion: "2010-09-09"
Description: "NAT Gateway"
Parameters:
  SsubnetCidr:
    Type: String
    Description: Ip
    Default: 10.0.0.4/16
Resources:
  SNatGateWayEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: !Ref SsubnetCidr
  SurekhaNatGateWay:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt SNatGateWayEIP.AllocationId
      SubnetId: !ImportValue ImportSubnetId
      Tags:
        - Key: User
          Value: surekha.janjanam
  SurekhaSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      CidrBlock: 10.0.1.8/24
      AvailabilityZone: us-east-1a
      Tags:
        - Key: User
          Value: surekha.janjanam
      VpcId: !ImportValue ImportVpcId
  SurekhaRouteTable1:
      Type: AWS::EC2::RouteTable
      Properties: 
        VpcId: !ImportValue ImportVpcId
  SurekhaRoute1:
      Type: AWS::EC2::Route
      Properties: 
        NatGatewayId: !Ref SurekhaNatGateWay
        RouteTableId: !Ref SurekhaRouteTable1
        DestinationCidrBlock: 0.0.0.0/16
  SRouteNATGateway:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref SurekhaRouteTable1
      DestinationCidrBlock: '0.0.0.0/16'
      NatGatewayId: !Ref SurekhaNatGateWay
  SurekhaEc2Instance1:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-05fa00d4c63e32376
      AvailabilityZone: us-east-1a
      KeyName: SurekhaKeyPair
      Tags:
        - Key: User
          Value: surekha.janjanam
      SubnetId: !Ref SurekhaSubnet2
