AWSTemplateFormatVersion: "2010-09-09"
Description: "Security Group"
Resources:
  SurekhaEc2Instance:
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      ImageId: ami-05fa00d4c63e32376
      AvailabilityZone: us-east-1a
      KeyName: SurekhaKeyPair
      Tags:
        - Key: User
          Value: surekha.janjanam
      SubnetId: !ImportValue ImportSubnetId
      SecurityGroupIds:
        - !Ref SurekhaSGPing
  SurekhaSGPing:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SeurityGroup to test ping
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.0.0/24
        - IpProtocol: icmp
          FromPort: 8
          ToPort: -1
          CidrIp: 10.0.0.0/24
      Tags: 
        - Key: User
          Value: surekha.janjanam
      VpcId: !ImportValue ImportVpcId
  SurekhaEIP:
    Type: AWS::EC2::EIP
    Properties: 
      InstanceId: !Ref SurekhaEc2Instance  