AWSTemplateFormatVersion: "2010-09-09"
Description: "Add privileges to the role"
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: hari2567
  IamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - iam.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: InlinePolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                - "iam:Get*"
                - "iam:List*"
                Resource: "arn:aws:iam::324320755747:role/harish789-IamRootRole-16O43XZ1BRJ8R"
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
      RoleName: harish789-IamRootRole-16O43XZ1BRJ8R 