AWSTemplateFormatVersion: "2010-09-09"
Description: Adding Network ACL
Parameters:
  subnetCidr:
    Type: String
    Description: Ip
    Default: 10.0.0.8/16
  MyVpc:
    Description: Connecting vpc
    Type: String
    Default: vpc-00cb2f8dba00ee08f
Resources:
  MyNetworkAcls:
    Type: AWS::EC2::NetworkAcl
    Properties: 
      VpcId: !Ref MyVpc
      Tags:
        - Key: User
          Value: shivani.k
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security Group for EC2
      GroupName: SecurityGroup2
      SecurityGroupIngress:
        - IpProtocol: All
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8
          ToPort: 22
          CidrIp: 192.0.2.0/24
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 2
          ToPort: 443
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: User
          Value: shivani.k
      VpcId: !Ref MyVpc