AWSTemplateFormatVersion: "2010-09-09"
Description: "Security group to Instance"
Parameters:
  InstanceTypeId:
    Type: String
    Description: Instance type t2 selection
    Default: t2.micro
    AllowedValues: 
        - t2.micro
        - t2.small
        - t2.medium
  MyInstanceAmiId:
    Type: String
    Description: AMI Of Linux OS
    Default: ami-05fa00d4c63e32376
  KeyName:
    Description: Name of key pair in AWS
    Type: 'AWS::EC2::KeyPair::KeyName'
    Default: shivanikeypair
  MyVPC:
    Description: Connecting vpc
    Type: String
    Default: vpc-0c968614a585420e3
Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref InstanceTypeId
      KeyName: !Ref KeyName
      ImageId: !Ref MyInstanceAmiId
      Tags:
            - Key: User
              Value: kolikacharla.shivani         
            - Key: stelligent-u-lesson
              Value: '4'
            - Key: stelligent-u-lab
              Value: '4.1.1' 
      SubnetId: !ImportValue ImportSubnetId1
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: SG to test ping
      SecurityGroupIngress:
          - IpProtocol: tcp
            FromPort: 22
            ToPort: 22
            CidrIp: 10.0.0.0/24
          - IpProtocol: icmp
            FromPort: 8
            ToPort: -1
            CidrIp: 10.0.0.0/24
      VpcId: !Ref MyVPC
Outputs:
  InstanceId:
    Value: !Ref MyInstance
  PrivateIp:
    Value: !GetAtt MyInstance.PrivateIp
 