AWSTemplateFormatVersion: "2010-09-09"
Description: "enter pseudo parameters"
Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Join [ '-', [ !Ref 'AWS::StackName', !Ref 'AWS::Region', !Ref 'AWS::URLSuffix']]
Outputs:
    StackName:
      Value: !Ref "AWS::StackName"
    Region:
      Value: !Ref "AWS::Region"
    URLSuffix:
      Value: !Ref "AWS::URLSuffix"
 

 #command:aws cloudformation update-stack --no-verify-ssl --profile temp --stack-name shivaniss1 --template-body "file://C:\Users\kolikacharla.shivani\Documents\cloudformation template\s3-bucket-lab-1.1.3.yaml