AWSTemplateFormatVersion: "2010-09-09"
Description: "Importing another Stack's Exports"
Parameters:
  UserName:
    Type: String
    Default: surekha2
  UserPassword:
    Type: String
    Default: Jvts888#
Resources:
  IamUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Ref UserName
      LoginProfile:
        Password: !Ref UserPassword
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
Outputs:
  OutputName:
    Description: "user name for the iam"
    Value: !Ref IamUser
    Export:
      Name: "ManagedPolicyArns"
    
