AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 parameter template creation"
Resources:
  MyS3NewBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref newfirstbucket1
Parameters:
  newfirstbucket1:
    Type: String
    