AWSTemplateFormatVersion: 2010-09-09
Resources:
  s3bucket1:
    Type: 'AWS::S3::Bucket'
    Properties:
      BucketName: elsa78
  RootRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
                Service: iam.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
      - PolicyName: InlinePolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - "s3:*"
              Resource: "*"
      ManagedPolicyArns:
      - 'arn:aws:iam::aws:policy/AmazonS3FullAccess'

        
